# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
        exclude: tests_requre/openshift_integration/test_data/*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.781
  #   hooks:
  #     - id: mypy
  #       args: [--no-strict-optional, --ignore-missing-imports]
  #       additional_dependencies: ["sqlalchemy-stubs"]
  # - repo: https://github.com/packit/pre-commit-hooks
  #   rev: master
  #   hooks:
  #     - id: check-rebase
  #       args:
  #         - git://github.com/packit/tokman.git
